# Generated by Django 5.2.6 on 2026-04-03 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_cartitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartitem',
            options={},
        ),
    ]
