# Generated by Django 5.2.6 on 2026-04-04 04:21

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_cartitem_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='orderitem_images'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='product_images'),
        ),
        migrations.AlterField(
            model_name='reviewimage',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='review_images'),
        ),
    ]
